import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import DataTable from 'react-data-table-component';
import Footer from '../../components/Footer'
import Header from '../../components/Header'
import Search from '../../components/Search'
import { axiosInstance } from '../../utils/axios'



export const getServerSideProps = async (context) => {
    const idz = context.query.id
    try {
        const data = await(await axiosInstance.put(`api/controller/cinema/${idz}`)).data
       return {
         props: {
           data
         }
       };
   } catch (error:any) {
       return {
           props: {
               error: error.message
           },
       };
   }
     
   }

const Cinemas: NextPage = ({data}:any) => {    


const columns = [
      {
          name: 'movie name',
          selector: row => row.movies,
      },
      {
          name: 'duration',
          selector: row => row.duration,
      },
      {
          name: 'mon',
          selector: row => row.mon,
      },
      {
          name: 'tue',
          selector: row => row.tue,
      },
      {
          name: 'wed',
          selector: row => row.wed,
      },
      {
          name: 'thur',
          selector: row => row.thur,
      },
      {
          name: 'fri',
          selector: row => row.fri,
      },
      {
          name: 'sat',
          selector: row => row.sat,
      },
      {
          name: 'sun',
          selector: row => row.sun,
      },
  ];
    


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      
      <Search/>
    
    

   
    <div className="news-area section-padding-100-70">
        <div className="container">
            <h5><span style={{color:'grey'}}>Cinema name: </span><span>{data.cinema_id.name}</span></h5>
            <h5><span style={{color:'grey'}}>Location: </span><span>{data.cinema_id.state}</span></h5>
            <h5><span style={{color:'grey'}}>Address: </span><span>{data.cinema_id.address}</span></h5>
            <h5><span style={{color:'grey'}}>Showing: </span><span>{`movies showing from ${data.date}`}</span></h5>
            <div className="row">
                <div className="col-12 col-md-12">
                <DataTable
                    columns={columns}
                    data={data.movies}
                    striped={true}
                    pagination
                    fixedHeader
                    fixedHeaderScrollHeight='450px'
                    highlightOnHover
                />
                </div>
            </div>
        </div>
    </div>

    <Footer/>

    </div>
  )
}

export default Cinemas
