import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import AllLatestNews from '../../components/allLatestNews'
import Footer from '../../components/Footer'
import Header from '../../components/Header'
import Search from '../../components/Search'
import { axiosInstance } from '../../utils/axios'



export const getServerSideProps = async () => {
    
    try {
        const data = await(await axiosInstance.get("api/controller/post/getpost")).data
       return {
         props: {
           data
         }
       };
   } catch (error:any) {
       return {
           props: {
               error: error.message
           },
       };
   }
     
   }

const Cinemas: NextPage = ({data}:any) => {

    const [News, setNews] = useState<any[]>([])
    const router = useRouter()
    const {slug} = router.query
    const [NewCinema, setNewCinema] = useState<any[]>([])
    
    
    useEffect(() => {
        const news = data?.filter(x=>x.category === "News")
        const newNews = news?.slice(0,7)        
        setNews(newNews)
      }, [data])

    useEffect(() => {
        getCinemas()
    }, [slug])

    const getCinemas = async()=>{
        await axiosInstance.get(`api/controller/post/${slug}`).then((res)=>{
            setNewCinema(res.data)
        }).catch((err)=>{
            console.log(err.message);
        })
    }
    


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      
      <Search/>
    
    

   
    <div className="news-area section-padding-100-70">
        <div className="container">
            <div className="row">
                <div className="col-12 col-md-7 col-lg-8">

                <div className="intro-news-filter d-flex justify-content-between">
                {NewCinema.length > 0?  <h6>Search for &nbsp; &apos;{slug}&apos;</h6> : <h6>No search result for Post {slug}</h6>} 
                </div>

                  
                    {NewCinema?.map((data,i)=>(
                    <div className="single-blog-post d-flex flex-wrap style-5 mb-30" key={i}>
                        <div className="blog-thumbnail">
                        <Link href={`/post/${data?.slug}`}><a><img src={data?.image} alt="" style={{width:'100%',height:'130px',objectFit:'cover'}}/></a></Link>
                        </div>
                        <div className="blog-content" style={{marginTop:'1rem'}}>
                        <Link href={`/post/${data?.slug}`}><a className="post-title">{data?.title}</a></Link>
                        </div>
                    </div>
                    ))}
                </div>

                <div className="col-12 col-md-5 col-lg-4">
                   <AllLatestNews News={News}/>
                </div>
            </div>
        </div>
    </div>

    <Footer/>

    </div>
  )
}

export default Cinemas
